[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/sh"
